# Generated by Django 4.0.3 on 2022-03-19 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='boi',
            new_name='bio',
        ),
    ]
